---

- name: F5 ansible playground
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Include vars
      include_vars:
         file: vars.yml

    - name: Creating GTM Pool
      bigip_gtm_pool:
        name: "pool.{{ service_name }}.{{ vlan_name }}.{{ item }}"
        type: "{{ record_type }}"
        ttl: 3
        provider:
           server: "{{ inventory_hostname }}"
           validate_certs: "false"
        partition: "{{ partition }}"
        preferred_lb_method: round-robin
        alternate_lb_method: none
        fallback_lb_method: none
      with_items:
         - akl
         - wgt
