---

- name: F5 ansible playground
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Include template
      include_vars:
        file: cfg/template.yml

    - name: Debug credentials
      debug:
        msg: "Username is {{ username }} and password is {{ password }}"

    - name: Creating Datacenter {{ datacenter_name }}
      bigip_gtm_datacenter:
        user: "{{ username }}"
        password: "{{ password }}"
        server: "{{ gtm_server }}"
        validate_certs: no
        name: "{{ datacenter_name }}"

    - name: Creating VLAN {{ vlan_id }}
      bigip_vlan:
        # need to workout how to ensure no one makes a mistake here. Probably some logic somewhere.
        tagged_interface: 1.3
        name: "{{ vlan_name }}"
        tag: "{{ vlan_id }}"
        provider:
           user: "{{ username }}"
           password: "{{ password }}"
           server: "{{ gtm_server }}"
           validate_certs: no
      delegate_to: localhost

    - name: Creating GTM Pool {{ gtmpool_name }}
      bigip_gtm_pool:
        server: "{{ gtm_server }}"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        name: "{{ gtmpool_name }}"
        type: "{{ record_type }}"
      delegate_to: localhost

    - name: Creating new LTM pool
      bigip_pool:
        user: "{{ username }}"
        password: "{{ password }}"
        server: "{{ gtm_server }}"
        validate_certs: no
        name: "{{ ltmpool_name }}"
      delegate_to: localhost

    - name: Adding pool member in pool {{ ltmpool_name }}
      bigip_pool_member:
        user: "{{ username }}"
        password: "{{ password }}"
        server: "{{ gtm_server }}"
        validate_certs: no
        pool: "{{ ltmpool_name }}"
        host: "{{ item.host }}"
        port: 80
      loop: "{{ ltm_node_list }}"

#    - name: Renaming LTM nodes
#      bigip_node:
#        user: "{{ username }}"
#        password: "{{ password }}"
#        server: "{{ gtm_server }}"
#        validate_certs: no
#        host: "{{ item.host }}"
#        name: "{{ item.name }}"
      # preferably that we add a query to the bluecat during this stage before provisioning
#      loop: "{{ ltm_node_list }}"
#      delegate_to: localhost


    - name: Add new Virtual Server {{ vs_name }}
      bigip_virtual_server:
        user: "{{ username }}"
        password: "{{ password }}"
        server: "{{ gtm_server }}"
        validate_certs: no
        name: "{{ vs_name }}"
        destination: 10.10.10.10
        port: 443
        pool: "{{ ltmpool_name }}"

    - name: Creating GTM wide IP for {{ fqdn }}
      bigip_gtm_wide_ip:
        user: "{{ username }}"
        password: "{{ password }}"
        server: "{{ gtm_server }}"
        validate_certs: no
        name: "{{ fqdn }}"
        type: "{{ record_type }}"
        pool_lb_method: "{{ lb_method }}"
        pools:
          [ name: "{{ gtmpool_name }}" ]
      delegate_to: localhost
